version: "3.9" # spécifie la version de Docker Compose à utiliser

services:

  php-apache:
    container_name: php-apache_prod
    ports:
      - "80:80" # mappe le port 80 de l'hôte sur le port 80 du conteneur Apache
    build: './build/php'
    volumes:
      - ./www:/var/www/html
    networks:
      - db_net

  mysql:
    container_name: mysql_prod
    restart: always
    ports:
      - "3306:3306" # mappe le port 3306 de l'hôte sur le port 3306 du conteneur MySQL
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    volumes:
      - dbData:/var/lib/mysql # monte le volume dbData dans le conteneur MySQL
      - ./build/sql:/docker-entrypoint-initdb.d
    networks:
      - db_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_prod
    restart: always
    ports:
      - "8080:80" # mappe le port 8080 de l'hôte sur le port 80 du conteneur phpMyAdmin
    environment:
      PMA_HOST: mysql # spécifie le nom d'hôte du conteneur MySQL pour phpMyAdmin
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    networks:
      - db_net

networks:
  db_net:  # crée un réseau interne nommé db_net pour les conteneurs

volumes:
  www:
  dbData: