services:

  mysql:
    image: mysql:latest
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: i%E%6N4!xUYuBC!@uu6$78aX8
      MYSQL_DATABASE: enac-quiz
      MYSQL_USER: rocco
      MYSQL_PASSWORD: puzzle-sprung0-donut
    volumes:
      - db_data:/var/lib/mysql
      - ./chemin/vers/le/enac-quiz.sql:/docker-entrypoint-initdb.d/enac-quiz.sql

  apache:
    image: httpd:latest
    container_name: apache_prod
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_prod
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_mysql_root_password

volumes:
  db_data: